index:
    path: /
    controller: app\Controller\BlogController::index

login:
    path: /login
    controller: app\Controller\SecurityController::login

logout:
    path: /logout
    controller: app\Controller\SecurityController::logout


#app_blog_posts:
#  path: /blog/posts
#  controller: app\Controller\BlogController::getAll