index:
    path: /
    controller: app\Controller\BlogController::index

login:
    path: /login
    controller: app\Controller\SecurityController::login

#app_blog_posts:
#  path: /blog/posts
#  controller: app\Controller\BlogController::getAll